version: "3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: "always"
    command: --sql_mode=''
    # command: mysqld --sql_mode=''
    environment:
      - MYSQL_DATABASE=prod
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33060:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
      - "./db:/docker-entrypoint-initdb.d/"
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

